-- ─────────────────────────────────────────────────────────
-- Migration 009: 30 Puzzles for Chapter 4 (Loops)
-- ─────────────────────────────────────────────────────────

DO $$ 
DECLARE 
  ch4_id UUID;
BEGIN 
  -- Find the Chapter 4 ID
  SELECT id INTO ch4_id FROM chapters WHERE concept = 'loops' LIMIT 1;
  
  -- Clear any existing puzzles for Chapter 4 to prevent duplicates
  DELETE FROM puzzles WHERE chapter_id = ch4_id;

  -- ─── 10 Basic Puzzles (Position 1-10) ───
  INSERT INTO puzzles (chapter_id, story_context, question, code_snippet, options, correct_answer, explanation, xp_reward, difficulty, position, hint) VALUES
  (ch4_id, 'The staircase stretches upward. You decide to take 5 steps.', 'What is the standard loop to repeat an action 5 times?', 'for (var i = 0; i < 5; i++) { ... }', ARRAY['for loop', 'while loop', 'do-while loop', 'if loop'], 'for loop', 'The "for" loop is the most common way to iterate a specific number of times.', 10, 'basic', 1, 'It has three parts: start, condition, and step.'),
  (ch4_id, 'A collection of mysterious stones lies on the step.', 'How do you iterate through all items in a list called `stones`?', 'var stones = ["Ruby", "Jade"];', ARRAY['for (var s in stones)', 'while (stones)', 'if (stones.all)', 'for (var i = stones)'], 'for (var s in stones)', 'The "for-in" loop is the simplest way to iterate through a collection in Dart.', 10, 'basic', 2, 'Think of "for each stone in stones".'),
  (ch4_id, 'The wind whispers: "Repeat while the torch glows."', 'Which loop checks its condition BEFORE running the code?', '...', ARRAY['while', 'do-while', 'for-if', 'repeat'], 'while', 'A "while" loop checks the condition first; if it''s false, the code never runs.', 10, 'basic', 3, 'Check the gate before you enter.'),
  (ch4_id, 'Start at zero, go until ten.', 'What is the "condition" part of a for loop?', 'for (init; condition; increment)', ARRAY['condition', 'init', 'increment', 'body'], 'condition', 'The middle part of the for loop header determines when the loop stays active.', 10, 'basic', 4, 'It''s the "gatekeeper" of the loop.'),
  (ch4_id, 'One step higher at a time.', 'What does `i++` do in a loop?', 'for (int i = 0; i < 5; i++)', ARRAY['Increments i by 1', 'Decrements i by 1', 'Resets i to 0', 'Stops the loop'], 'Increments i by 1', 'The ++ operator adds one to the current value of the variable.', 10, 'basic', 5, 'It''s the same as i = i + 1.'),
  (ch4_id, 'A loop that never ends.', 'What happens if a loop''s condition is always true?', '...', ARRAY['Infinite loop', 'The app crashes', 'It runs once', 'Error'], 'Infinite loop', 'An infinite loop continues forever because its exit condition is never met.', 10, 'basic', 6, 'The Staircase that never ends!'),
  (ch4_id, 'Take a step, then check if you''re tired.', 'Which loop always runs AT LEAST once?', '...', ARRAY['do-while', 'while', 'for', 'forEach'], 'do-while', 'The "do-while" loop runs the body first, then checks the condition at the end.', 10, 'basic', 7, 'Action first, questions later.'),
  (ch4_id, 'Count the steps on the wall.', 'How many times will `for (int i=0; i<3; i++)` run?', '...', ARRAY['3', '2', '4', '0'], '3', 'It runs for i=0, i=1, and i=2. When i=3, the condition is false.', 10, 'basic', 8, 'Count carefully: 0, 1, 2... stop!'),
  (ch4_id, 'The countdown begin.', 'How to write a loop that starts at 5 and goes down to 1?', '...', ARRAY['for (int i=5; i>0; i--)', 'for (int i=1; i<5; i++)', 'while (i < 5)', 'None'], 'for (int i=5; i>0; i--)', 'Use a decrement operator (--) and a "greater than" condition to count down.', 10, 'basic', 9, 'Step down the stairs.'),
  (ch4_id, 'A single step of faith.', 'Can a for loop run exactly 1 time?', '...', ARRAY['Yes', 'No', 'Only if it errors', 'Only in Java'], 'Yes', 'By setting the condition carefully, a loop can run any number of times.', 10, 'basic', 10, 'Even 1 is a loop of one.');

  -- ─── 10 Intermediate Puzzles (Position 11-20) ───
  INSERT INTO puzzles (chapter_id, story_context, question, code_snippet, options, correct_answer, explanation, xp_reward, difficulty, position, hint) VALUES
  (ch4_id, 'A sudden obstacle on the stairs.', 'Which keyword immediately stops a loop?', '...', ARRAY['break', 'continue', 'exit', 'return'], 'break', 'The "break" keyword exits the current loop immediately, skipping remaining iterations.', 15, 'intermediate', 11, 'It "breaks" out of the cycle.'),
  (ch4_id, 'Skipping a broken step.', 'Which keyword skips the rest of the CURRENT iteration?', '...', ARRAY['continue', 'break', 'skip', 'next'], 'continue', 'The "continue" keyword jumps to the next iteration of the loop immediately.', 15, 'intermediate', 12, 'It "continues" to the next step.'),
  (ch4_id, 'The Summation Tablet.', 'How to add all numbers in `List<int> nums`?', 'var sum = 0;', ARRAY['for (var n in nums) sum += n;', 'nums.all()', 'sum = nums + nums', 'for (sum in nums)'], 'for (var n in nums) sum += n;', 'Using a loop to accumulate values is a fundamental pattern.', 15, 'intermediate', 13, 'Add each number to the total.'),
  (ch4_id, 'The Nested Sprials.', 'A loop inside another loop is called...?', '...', ARRAY['Nested loop', 'Double loop', 'Square loop', 'Recursion'], 'Nested loop', 'Nested loops are used for multi-dimensional data or repeating repetitions.', 15, 'intermediate', 14, 'A spiral within a spiral.'),
  (ch4_id, 'Searching for the Golden Step.', 'Find if "Gold" is in a list.', 'bool found = false;', ARRAY['for (var s in steps) if (s == "Gold") found = true;', 'steps.contains("Gold")', 'Both 1 and 2', 'None'], 'Both 1 and 2', 'A manual loop or a collection method like `contains` both work.', 15, 'intermediate', 15, 'Search every step!'),
  (ch4_id, 'The while(true) trap.', '`while (true) { if (ready) break; }` Is this valid?', '...', ARRAY['Yes', 'No', 'Only in loops', 'Infinite Error'], 'Yes', 'A while(true) loop is valid as long as there is a `break` or `return` inside.', 15, 'intermediate', 16, 'It waits until the condition is met.'),
  (ch4_id, 'The forEach whisper.', '`list.forEach(print);` What does this do?', 'var list = [1, 2];', ARRAY['Prints 1 and 2', 'Prints nothing', 'Crashes', 'Prints [1, 2]'], 'Prints 1 and 2', 'The forEach method applies a function to every item in the collection.', 15, 'intermediate', 17, 'A shortcut for a simple loop.'),
  (ch4_id, 'The Map Iteration.', 'How to loop through Map keys?', 'var map = {"a": 1};', ARRAY['for (var key in map.keys)', 'for (var key in map)', 'while (map.next)', 'Error'], 'for (var key in map.keys)', 'Maps are not directly iterable, but their `.keys` or `.values` properties are.', 15, 'intermediate', 18, 'Iterate through the labels, not the values.'),
  (ch4_id, 'The Loop Variable Update.', '`for (int i=0; i<10; i++) { i++; }` How many times?', '...', ARRAY['5', '10', 'Infinite', '0'], '5', 'Updating `i` manually inside the loop adds to the increment in the header.', 15, 'intermediate', 19, 'Double steps!'),
  (ch4_id, 'The do-while condition.', '`int x = 5; do { print(x); } while (x < 5);` What is printed?', '...', ARRAY['5', 'Nothing', 'Infinite 5s', 'Error'], '5', 'The body runs first, prints 5, then checks 5 < 5 (false) and stops.', 15, 'intermediate', 20, 'At least once, no matter what.');

  -- ─── 10 Advanced Puzzles (Position 21-30) ───
  INSERT INTO puzzles (chapter_id, story_context, question, code_snippet, options, correct_answer, explanation, xp_reward, difficulty, position, hint) VALUES
  (ch4_id, 'Escape from the Inner Spiral.', 'What allows you to "break" out of an INNER loop to an OUTER one?', '...', ARRAY['Labels (outer:)', 'Goto', 'Double break', 'Super break'], 'Labels (outer:)', 'Labels allow keywords like `break` and `continue` to target specific loops.', 20, 'advanced', 21, 'Tag the loop you want to target.'),
  (ch4_id, 'The Label Jump.', '`outer: for(...) { for(...) { break outer; } }` What happens?', '...', ARRAY['Exits both loops', 'Exits inner only', 'Error', 'Resets outer'], 'Exits both loops', 'Breaking to a label exits the loop associated with that label.', 20, 'advanced', 22, 'The jump goes straight through.'),
  (ch4_id, 'The Concurrent Curse.', 'Removing items from a list while looping through it often causes...?', '...', ARRAY['ConcurrentModificationError', 'Infinite loop', 'Nothing', 'Memory leak'], 'ConcurrentModificationError', 'You cannot modify a collection while iterating over it with a standard loop.', 20, 'advanced', 23, 'Don''t pull the rug while standing on it!'),
  (ch4_id, 'The Asynchronous Ascent.', 'How do you iterate over a Stream of data?', 'Stream<int> steps = ...;', ARRAY['await for (var s in steps)', 'for (var s in steps)', 'while (await steps)', 'None'], 'await for (var s in steps)', 'The `await for` loop is used to handle values arriving asynchronously from a Stream.', 20, 'advanced', 24, 'Wait for each new step to appear.'),
  (ch4_id, 'The Generator Scroll.', 'Which keyword emits a value in a `sync*` generator?', 'Iterable<int> count() sync* { ... }', ARRAY['yield', 'return', 'emit', 'send'], 'yield', '`yield` returns a value from a generator function without ending the execution.', 20, 'advanced', 25, 'Give a value, then keep going.'),
  (ch4_id, 'Functional Filtering.', '`steps.where((s) => s.isSafe).forEach(print);` What is this?', '...', ARRAY['Functional programming', 'Traditional loop', 'Nested branch', 'Error'], 'Functional programming', 'Combining collection methods like `where` and `forEach` is a functional style.', 20, 'advanced', 26, 'Elegant, but still a loop underneath.'),
  (ch4_id, 'The Memory Loom.', 'Which is memory-efficient for building strings in a loop?', '...', ARRAY['StringBuffer', '+=', 'String.join', 'String.fill'], 'StringBuffer', 'Adding strings with `+=` creates new objects every time; `StringBuffer` is much faster.', 20, 'advanced', 27, 'Don''t waste threads.'),
  (ch4_id, 'The Recursive Staircase.', 'A function that calls itself is called...?', '...', ARRAY['Recursion', 'Self-pointing', 'Mirror loop', 'The Spiral'], 'Recursion', 'Recursion is an alternative to loops that uses the call stack to repeat actions.', 20, 'advanced', 28, 'Solving the stairs by solving smaller stairs.'),
  (ch4_id, 'The Iterable Property.', 'Does `[1, 2, 3].map((x) => x * 2);` run immediately?', '...', ARRAY['No (it is lazy)', 'Yes', 'Only in loops', 'Error'], 'No (it is lazy)', 'Methods like `map` return a lazy `Iterable` that only runs when accessed.', 20, 'advanced', 29, 'Wait until someone actually looks at it.'),
  (ch4_id, 'The Infinite Loop safety.', 'What is the "Halting Problem" (Computer Science)?', '...', ARRAY['Cannot always detect infinite loops', 'Loops are slow', 'Memory limit', 'Formatting error'], 'Cannot always detect infinite loops', 'It is formally proven that a program cannot always determine if another will halt.', 20, 'advanced', 30, 'Even magic has its limits.');
END $$;
